dropdown_data = {"region": {"Worldwide": "",
                            "Afghanistan": "AF",
                            "Albania": "AL",
                            "Algeria": "DZ",
                            "American Samoa": "AS",
                            "Andorra": "AD",
                            "Angola": "AO",
                            "Anguilla": "AI",
                            "Antarctica": "AQ",
                            "Antigua & Barbuda": "AG",
                            "Argentina": "AR",
                            "Armenia": "AM",
                            "Aruba": "AW",
                            "Australia": "AU",
                            "Austria": "AT",
                            "Azerbaijan": "AZ",
                            "Bahamas": "BS",
                            "Bahrain": "BH",
                            "Bangladesh": "BD",
                            "Barbados": "BB",
                            "Belarus": "BY",
                            "Belgium": "BE",
                            "Belize": "BZ",
                            "Benin": "BJ",
                            "Bermuda": "BM",
                            "Bhutan": "BT",
                            "Bolivia": "BO",
                            "Bonaire, Sint Eustatius & Saba": "BQ",
                            "Bosnia & Herzegovina": "BA",
                            "Botswana": "BW",
                            "Bouvet Island": "BV",
                            "Brazil": "BR",
                            "British Indian Ocean Territory": "IO",
                            "Brunei": "BN",
                            "Bulgaria": "BG",
                            "Burkina Faso": "BF",
                            "Burundi": "BI",
                            "Cambodia": "KH",
                            "Cameroon": "CM",
                            "Canada": "CA",
                            "Cape Verde": "CV",
                            "Cayman Islands": "KY",
                            "Central African Republic": "CF",
                            "Chad": "TD",
                            "Chile": "CL",
                            "China": "CN",
                            "Christmas Island": "CX",
                            "Cocos (Keeling) Islands": "CC",
                            "Colombia": "CO",
                            "Comoros": "KM",
                            "Congo": "CG",
                            "Democratic Rep. of the Congo": "CD",
                            "Cook Islands": "CK",
                            "Costa Rica": "CR",
                            "Croatia": "HR",
                            "Cuba": "CU",
                            "Curaçao": "CW",
                            "Cyprus": "CY",
                            "Czech Republic": "CZ",
                            "Côte d’Ivoire": "CI",
                            "Denmark": "DK",
                            "Djibouti": "DJ",
                            "Dominica": "DM",
                            "Dominican Republic": "DO",
                            "Ecuador": "EC",
                            "Egypt": "EG",
                            "El Salvador": "SV",
                            "Equatorial Guinea": "GQ",
                            "Eritrea": "ER",
                            "Estonia": "EE",
                            "Eswatini": "SZ",
                            "Ethiopia": "ET",
                            "Falkland Islands (Malvinas)": "FK",
                            "Faroe Islands": "FO",
                            "Fiji": "FJ",
                            "Finland": "FI",
                            "France": "FR",
                            "French Guiana": "GF",
                            "French Polynesia": "PF",
                            "French Southern Territories": "TF",
                            "Gabon": "GA",
                            "Gambia": "GM",
                            "Georgia": "GE",
                            "Germany": "DE",
                            "Ghana": "GH",
                            "Gibraltar": "GI",
                            "Greece": "GR",
                            "Greenland": "GL",
                            "Grenada": "GD",
                            "Guadeloupe": "GP",
                            "Guam": "GU",
                            "Guatemala": "GT",
                            "Guernsey": "GG",
                            "Guinea": "GN",
                            "Guinea-Bissau": "GW",
                            "Guyana": "GY",
                            "Haiti": "HT",
                            "Heard & McDonald Islands": "HM",
                            "Vatican City": "VA",
                            "Honduras": "HN",
                            "Hong Kong": "HK",
                            "Hungary": "HU",
                            "Iceland": "IS",
                            "India": "IN",
                            "Indonesia": "ID",
                            "Iran": "IR",
                            "Iraq": "IQ",
                            "Ireland": "IE",
                            "Isle of Man": "IM",
                            "Israel": "IL",
                            "Italy": "IT",
                            "Jamaica": "JM",
                            "Japan": "JP",
                            "Jersey": "JE",
                            "Jordan": "JO",
                            "Kazakhstan": "KZ",
                            "Kenya": "KE",
                            "Kiribati": "KI",
                            "North Korea": "KP",
                            "South Korea": "KR",
                            "Kuwait": "KW",
                            "Kyrgyzstan": "KG",
                            "Laos": "LA",
                            "Latvia": "LV",
                            "Lebanon": "LB",
                            "Lesotho": "LS",
                            "Liberia": "LR",
                            "Libya": "LY",
                            "Liechtenstein": "LI",
                            "Lithuania": "LT",
                            "Luxembourg": "LU",
                            "Macao": "MO",
                            "Macedonia": "MK",
                            "Madagascar": "MG",
                            "Malawi": "MW",
                            "Malaysia": "MY",
                            "Maldives": "MV",
                            "Mali": "ML",
                            "Malta": "MT",
                            "Marshall Islands": "MH",
                            "Martinique": "MQ",
                            "Mauritania": "MR",
                            "Mauritius": "MU",
                            "Mayotte": "YT",
                            "Mexico": "MX",
                            "Micronesia": "FM",
                            "Moldova": "MD",
                            "Monaco": "MC",
                            "Mongolia": "MN",
                            "Montenegro": "ME",
                            "Montserrat": "MS",
                            "Morocco": "MA",
                            "Mozambique": "MZ",
                            "Myanmar": "MM",
                            "Namibia": "NA",
                            "Nauru": "NR",
                            "Nepal": "NP",
                            "Netherlands": "NL",
                            "New Caledonia": "NC",
                            "New Zealand": "NZ",
                            "Nicaragua": "NI",
                            "Niger": "NE",
                            "Nigeria": "NG",
                            "Niue": "NU",
                            "Norfolk Island": "NF",
                            "Northern Mariana Islands": "MP",
                            "Norway": "NO",
                            "Oman": "OM",
                            "Pakistan": "PK",
                            "Palau": "PW",
                            "Palestine": "PS",
                            "Panama": "PA",
                            "Papua New Guinea": "PG",
                            "Paraguay": "PY",
                            "Peru": "PE",
                            "Philippines": "PH",
                            "Pitcairn": "PN",
                            "Poland": "PL",
                            "Portugal": "PT",
                            "Puerto Rico": "PR",
                            "Qatar": "QA",
                            "Romania": "RO",
                            "Russia": "RU",
                            "Rwanda": "RW",
                            "Reunion": "RE",
                            "St. Barthélemy": "BL",
                            "Saint Helena, Ascension & Tristan da Cunha": "SH",
                            "Saint Kitts & Nevis": "KN",
                            "Saint Lucia": "LC",
                            "Saint Martin": "MF",
                            "Saint Pierre & Miquelon": "PM",
                            "Saint Vincent & the Grenadines": "VC",
                            "Samoa": "WS",
                            "San Marino": "SM",
                            "Sao Tome & Principe": "ST",
                            "Saudi Arabia": "SA",
                            "Senegal": "SN",
                            "Serbia": "RS",
                            "Seychelles": "SC",
                            "Sierra Leone": "SL",
                            "Singapore": "SG",
                            "Sint Maarten": "SX",
                            "Slovakia": "SK",
                            "Slovenia": "SI",
                            "Solomon Islands": "SB",
                            "Somalia": "SO",
                            "South Africa": "ZA",
                            "South Georgia & the South Sandwich Islands": "GS",
                            "South Sudan": "SS",
                            "Spain": "ES",
                            "Sri Lanka": "LK",
                            "Sudan": "SD",
                            "Suriname": "SR",
                            "Svalbard & Jan Mayen": "SJ",
                            "Sweden": "SE",
                            "Switzerland": "CH",
                            "Syria": "SY",
                            "Taiwan": "TW",
                            "Tajikistan": "TJ",
                            "Tanzania": "TZ",
                            "Thailand": "TH",
                            "Timor-Leste": "TL",
                            "Togo": "TG",
                            "Tokelau": "TK",
                            "Tonga": "TO",
                            "Trinidad & Tobago": "TT",
                            "Tunisia": "TN",
                            "Turkey": "TR",
                            "Turkmenistan": "TM",
                            "Turks & Caicos Islands": "TC",
                            "Tuvalu": "TV",
                            "Uganda": "UG",
                            "Ukraine": "UA",
                            "United Arab Emirates": "AE",
                            "United Kingdom": "GB",
                            "United States": "US",
                            "U.S. Minor Outlying Islands": "UM",
                            "Uruguay": "UY",
                            "Uzbekistan": "UZ",
                            "Vanuatu": "VU",
                            "Venezuela": "VE",
                            "Viet Nam": "VN",
                            "Virgin Islands, British": "VG",
                            "Virgin Islands, U.S.": "VI",
                            "Wallis & Futuna": "WF",
                            "Western Sahara": "EH",
                            "Yemen": "YE",
                            "Zambia": "ZM",
                            "Zimbabwe": "ZW",
                            "Åland Islands": "AX"},
"stype": {"Web Search": "", "Image Search": "images", "News Search": "news", "Google Shopping": "froogle", "Youtube Search": "youtube"},
"scat": {"All Categories": "",
         "Arts & Entertainment": "3",
         "Autos & Vehicles": "47",
         "Beauty & Fitness": "44",
         "Books & Literature": "22",
         "Business & Industrial": "12",
         "Computers & Electronics": "5",
         "Finance": "7",
         "Food & Drink": "71",
         "Games": "8",
         "Health": "45",
         "Hobbies & Leisure": "65",
         "Home & Garden": "11",
         "Internet & Telecom": "13",
         "Jobs & Education": "958",
         "Law & Government": "19",
         "News": "16",
         "Online Communities": "299",
         "People & Society": "14",
         "Pets & Animals": "66",
         "Real Estate": "29",
         "Reference": "533",
         "Science": "174",
         "Shopping": "18",
         "Sports": "20",
         "Travel": "67"
         }}
